import { Timestamp } from 'firebase/firestore';
export interface Cat {
  //Auto Generated By Cloud Function
  id?: string;
  createdAt?: Timestamp;
  createdDate?: string;
  createdBy?: string;

  //Core Fields
  type: string;
  name: string;
  colors: string[];
}
